name: Process incoming issues

on:
  issues:
    types: [ opened ]
  workflow_dispatch:
    inputs:
      issue_number:
        description: Issue number
        required: true
        type: number

env:
  GQL_HEADERS: "{headers: {'GraphQL-Features': 'issue_types'}}"
  ISSUE_TYPE_TASK_ID: IT_kwDOABIuus4AAqnX

jobs:
  set-default-issue-type:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    if: ${{ ! github.event.issue.pull_request }}

    permissions:
      issues: write

    steps:
      - uses: actions/github-script@v7
        id: get-issue-type
        with:
          script: |
            return github.graphql(`
              query {
                repository(owner: "${context.repo.owner}", name: "${context.repo.repo}") {
                  issue(number: ${{ inputs.issue_number != '' && inputs.issue_number || github.event.issue.number }}) {
                    issueType {
                      name
                    }
                    id
                  }
                }
              }
            `, ${{ env.GQL_HEADERS }})

      - run: echo "${{ steps.get-issue-type.outputs.result }}"

      - uses: actions/github-script@v7
        id: set-issue-type
        if: ${{ fromJson(steps.get-issue-type.outputs.result).repository.issue.issueType.name == '' }}
        with:
          script: |
            return github.graphql(`
              mutation {
                updateIssueIssueType(input: {
                  issueId: "${{ fromJson(steps.get-issue-type.outputs.result).repository.issue.id }}",
                  issueTypeId: "${{ env.ISSUE_TYPE_TASK_ID }}"
                }) {
                  issue {
                    id
                  }
                }
              }
            `, ${{ env.GQL_HEADERS }})

      - run: |
          gh issue edit ${{ inputs.issue_number != '' && inputs.issue_number || github.event.issue.number }} \
            --milestone "Future Releases"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
