name: Process incoming PRs

on:
  pull_request_target:
    types: [ opened ]

jobs:
  label-new-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      pull-requests: write

      # https://github.com/cli/cli/issues/6274
      repository-projects: read

    steps:
      - run: |
          gh pr edit ${{ github.event.pull_request.number }}  \
            --add-label "needs triage,prio: medium" \
            --milestone "Future Releases"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
